### ISSUE TITLE
Error in Terminal

### ISSUE THREAD

**Issue by GitHubProgramCode** [AtlasWHHV/GeneratorPlotsAlt#14]
**Unknown error**
Does anyone know what this means and is everyone getting it?  
"TUnixSystem::UnixTcpCo...  ERROR    connect (rucio-lb-prod.cern.ch:18762)  (Connection timed out)."
Everything seems to work so I'm thinking this is waiting for something else that we haven't put in there yet, but will later on down the road?

**Comment by AlexSchuy** [comment]
I'm not sure what part of the code this issue refers to, but if it is PlotGeneratorQuantities, I believe this issue was resolved and should be closed.
