### ISSUE TITLE
Error when running PlotGeneratorQuantities

### ISSUE THREAD

**Issue by GitHubProgramCode** [AtlasWHHV/GeneratorPlotsAlt#16]
**The following is only for the Branch AttemptAddJetsAndHistograms**
When I try to run PlotGeneratorQuantities, the process is aborted.  I get several warnings and errors:
1) WARNING No metadata available for branch: AntiKt4EMTopoJets
2) WARNING Branch "AntiKt4EMTopoJets" not available on input
3) WARNING Couldn't (const) retrieve "DataVector<xAOD::Jet_v1>/AntiKt4EMTopoJets"

I'll post the rest on FB.

**Comment by AlexSchuy** [comment]
PlotGeneratorQuantities is working on the master branch, I assume this issue should be closed.
