### ISSUE TITLE
Cannot compile GeneratorPlotsAlt for Branch AttemptAddJetsAndHistograms when certain lines aren't commented out

### ISSUE THREAD

**Issue by GitHubProgramCode** [AtlasWHHV/GeneratorPlotsAlt#17]
Several lines of code have been added so that the Histograms will actually appear and plot.  But when I leave these in, it won't compile.  The lines are are in PlotGeneratorQuantities.cxx are the following:
Lines 48-50
Lines 80-85

**Comment by AlexSchuy** [comment]
Histograms in the master branch are working, I assume this issue should be closed?
