### ISSUE TITLE
Indentations and Brackets

### ISSUE THREAD

**Issue by GitHubProgramCode** [AtlasWHHV/GeneratorPlotsAlt#23]
This is a Code Cleanup topic: correct indentations so the code is easier to read, especially of ifs/fors beginning line 205 of the MyxAODAnalysis.cxx.  Also correct the indentation of the brackets.

**Comment by AlexSchuy** [comment]
This is fixed in the lepton_plots fork. I adopted the style that I think is most prominent in the code, which is: 2 spaces for indentation, brackets on their own line, three spaces between method definitions, etc.
